# Generated by Django 5.0.2 on 2024-02-25 00:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('papellido', models.CharField(max_length=30, verbose_name='Primer Apellido')),
                ('sapellido', models.CharField(max_length=30, verbose_name='Segundo Apellido')),
                ('edad', models.CharField(max_length=2, verbose_name='Edad')),
                ('sexo', models.CharField(max_length=1, verbose_name='Sexo')),
                ('ci', models.CharField(max_length=11, verbose_name='Número de Identidad')),
                ('note', models.TextField(verbose_name='Nota')),
                ('localidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='localidad.poblado')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
