# Generated by Django 5.0.2 on 2024-04-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='historicalempleados',
            name='edad',
        ),
        migrations.AlterField(
            model_name='empleados',
            name='color_piel',
            field=models.CharField(blank=True, default=None, max_length=1, null=True, verbose_name='Color de la piel'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='sexo',
            field=models.CharField(default=None, max_length=1, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='historicalempleados',
            name='color_piel',
            field=models.CharField(blank=True, default=None, max_length=1, null=True, verbose_name='Color de la piel'),
        ),
        migrations.AlterField(
            model_name='historicalempleados',
            name='sexo',
            field=models.CharField(default=None, max_length=1, null=True, verbose_name='Sexo'),
        ),
    ]
