# Generated by Django 5.0.2 on 2024-04-29 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
        ('organizacion', '0003_areadpto_jefe'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='areadptoo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacion.areadpto'),
        ),
        migrations.AddField(
            model_name='historicalempleados',
            name='areadptoo',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizacion.areadpto'),
        ),
    ]
