# Generated by Django 5.0.2 on 2024-05-01 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_initial'),
        ('otros', '0002_pase_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='pase',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otros.pase', verbose_name='Pase (RTD)'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='turno',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otros.turno', verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='historicalempleados',
            name='pase',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='otros.pase', verbose_name='Pase (RTD)'),
        ),
        migrations.AlterField(
            model_name='historicalempleados',
            name='turno',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='otros.turno', verbose_name='Turno'),
        ),
    ]
