# Generated by Django 5.0.2 on 2024-04-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_remove_empleados_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='ci',
            field=models.CharField(blank=True, default='', max_length=11, null=True, unique=True, verbose_name='Número de Identidad'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='sexo',
            field=models.CharField(blank=True, default=None, max_length=1, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='historicalempleados',
            name='ci',
            field=models.CharField(blank=True, db_index=True, default='', max_length=11, null=True, verbose_name='Número de Identidad'),
        ),
        migrations.AlterField(
            model_name='historicalempleados',
            name='sexo',
            field=models.CharField(blank=True, default=None, max_length=1, null=True, verbose_name='Sexo'),
        ),
    ]
