# Generated by Django 5.0.2 on 2024-04-29 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_empleados_areadptoo_historicalempleados_areadptoo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleados',
            old_name='areadptoo',
            new_name='areadpt',
        ),
        migrations.RenameField(
            model_name='historicalempleados',
            old_name='areadptoo',
            new_name='areadpt',
        ),
    ]
