# Generated by Django 5.0.2 on 2024-04-29 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_remove_empleados_proyectos_and_more'),
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='proyectos',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacion.proyectos'),
        ),
        migrations.AddField(
            model_name='historicalempleados',
            name='proyectos',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizacion.proyectos'),
        ),
    ]
