# Generated by Django 5.0.2 on 2024-05-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empleados',
            name='state',
            field=models.CharField(blank=True, choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], default='Salida', max_length=10, null=True, verbose_name='Entrada/Salida'),
        ),
        migrations.AddField(
            model_name='historicalempleados',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalempleados',
            name='state',
            field=models.CharField(blank=True, choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], default='Salida', max_length=10, null=True, verbose_name='Entrada/Salida'),
        ),
    ]
