# Generated by Django 5.0.2 on 2024-05-05 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_alter_empleados_pase_alter_empleados_turno_and_more'),
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='cargo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacion.cargos', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='especialidad',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacion.especialidades', verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='historicalempleados',
            name='cargo',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizacion.cargos', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='historicalempleados',
            name='especialidad',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizacion.especialidades', verbose_name='Especialidad'),
        ),
    ]
