# Generated by Django 5.0.2 on 2024-04-29 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_rename_areadptoo_empleados_areadpt_and_more'),
        ('organizacion', '0003_areadpto_jefe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='areadpt',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacion.areadpto', verbose_name='Area o departamento'),
        ),
        migrations.AlterField(
            model_name='historicalempleados',
            name='areadpt',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizacion.areadpto', verbose_name='Area o departamento'),
        ),
    ]
