# Generated by Django 5.0.2 on 2024-05-06 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_empleados_cargo_empleados_especialidad_and_more'),
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='proyectos',
        ),
        migrations.RemoveField(
            model_name='historicalempleados',
            name='proyectos',
        ),
        migrations.AddField(
            model_name='empleados',
            name='proyecto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacion.proyectos', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='historicalempleados',
            name='proyecto',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizacion.proyectos', verbose_name='Proyecto'),
        ),
    ]
