# Generated by Django 5.0.2 on 2024-04-14 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_alter_empleados_ci_alter_historicalempleados_ci'),
        ('localidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='municipio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='localidad.municipio', verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='provincia',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='localidad.provincia', verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='historicalempleados',
            name='municipio',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='localidad.municipio', verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='historicalempleados',
            name='provincia',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='localidad.provincia', verbose_name='Provincia'),
        ),
    ]
