# Generated by Django 5.0.2 on 2024-04-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_alter_empleados_proyectos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='apartamento',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Apartamento de albergado'),
        ),
        migrations.AlterField(
            model_name='historicalempleados',
            name='apartamento',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Apartamento de albergado'),
        ),
    ]
