# Generated by Django 5.0.2 on 2024-02-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('papellido', models.CharField(max_length=30)),
                ('sapellido', models.CharField(max_length=30)),
                ('edad', models.CharField(max_length=2)),
                ('sexo', models.CharField(max_length=1)),
                ('ci', models.CharField(max_length=11)),
                ('note', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
