# Generated by Django 5.0.2 on 2024-02-11 03:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0002_trabajador_updated_at_alter_trabajador_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
