# Generated by Django 5.0.2 on 2024-02-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0004_rename_create_at_trabajador_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='ci',
            field=models.CharField(max_length=11, verbose_name='Número de Identidad'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='edad',
            field=models.CharField(max_length=2, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='nombre',
            field=models.CharField(max_length=60, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='note',
            field=models.TextField(verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='papellido',
            field=models.CharField(max_length=30, verbose_name='Primer Apellido'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='sapellido',
            field=models.CharField(max_length=30, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='sexo',
            field=models.CharField(max_length=1, verbose_name='Sexo'),
        ),
    ]
