# Generated by Django 5.0.2 on 2024-05-20 02:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEntradaSalida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('fecha_y_hora_entrada', models.DateTimeField()),
                ('fecha_y_hora_salida', models.DateTimeField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleados')),
            ],
            options={
                'verbose_name': 'Registro de entrada y salida',
                'verbose_name_plural': 'Registros de entrada y salida',
                'ordering': ['created_at'],
            },
        ),
    ]
