# Generated by Django 5.0.2 on 2024-05-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroentradasalida',
            name='fecha_y_hora_entrada',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha y Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='registroentradasalida',
            name='fecha_y_hora_salida',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha y Hora de Salida'),
        ),
    ]
