# Generated by Django 5.0.2 on 2024-05-20 14:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_alter_registroentradasalida_fecha_y_hora_entrada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraEntradaSalida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('hora_entrada', models.TimeField(blank=True, default=None, null=True, verbose_name='Hora de Entrada')),
                ('hora_salida', models.TimeField(blank=True, default=None, null=True, verbose_name='Hora de Salida')),
            ],
            options={
                'verbose_name': 'Hora de entrada y salida',
                'verbose_name_plural': 'Horas de entrada y salida',
                'ordering': ['created_at'],
            },
        ),
    ]
