# Generated by Django 5.0.2 on 2024-06-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_horaentradasalida'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaentradasalida',
            name='dia_semana',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], default='Lunes', max_length=10),
        ),
    ]
